version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [unique, not_null]
      - name: email
        tests: [not_null]

  - name: stg_stores
    columns:
      - name: store_id
        tests: [unique, not_null]

  - name: stg_products
    columns:
      - name: product_id
        tests: [unique, not_null]
      - name: unit_price
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false

  - name: stg_employees
    columns:
      - name: employee_id
        tests: [unique, not_null]
      - name: store_id
        tests:
          - relationships:
              to: ref('stg_stores')
              field: store_id

  - name: stg_orders
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customers')
              field: customer_id

  - name: stg_order_items
    columns:
      - name: order_item_id
        tests: [unique, not_null]
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: quantity
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
